### PR TITLE
enable jtcop

### LINKED ISSUE #9: pom.xml:215-227: enable jtcop--> <plugin>-->...
The puzzle `6-a2e5fba8` from #6 has to be resolved: 

https://github.com/eo-cqrs/eokson/blob/09f627da09926feed723e482d897d3a1fb0fcc6b/pom.xml#L215-L227

The puzzle was created by @rultor on 15-Jun-23. 

Estimate: 45 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

### PR DESCRIPTION
**Pull request by h1alexbel**
closes #9 

---

## PR-Codex overview
This PR focuses on updating a test method name and adding a Maven plugin. 

### Detailed summary
- Renamed the test method `readJsonFromFileInRightFormat` to `readsJsonFromFileInRightFormat`.
- Added the Maven plugin `jtcop-maven-plugin` to the `pom.xml` file.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by zoeself** [comment]
@h1alexbel thank you for your Pull Request. I'll assign someone to review it soon. 

 If this PR solves a ``todo`` from the code, please don't forget to remove it.

**Comment by zoeself** [comment]
@h1alexbel please review this Pull Request. Deadline (when it should be merged or closed) is ``2023-07-07T11:19:05.758066``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by h1alexbel** [comment]
@rultor merge

**Comment by zoeself** [comment]
@h1alexbel thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
