### PR TITLE
failOnError false

### LINKED ISSUE #47: pom.xml:241: failOnError set to true -->
The puzzle `10-1f6ed2c0` from #10 has to be resolved: 

https://github.com/eo-cqrs/eokson/blob/01048b5fde649507109e720e4fbb815c13dddd2a/pom.xml#L241-L241

The puzzle was created by @h1alexbel on 04-Jul-23. 

Estimate: 15 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

### PR DESCRIPTION
**Pull request by h1alexbel**
closes #47 

---

## PR-Codex overview
This PR focuses on adding a new dependency and annotation to the codebase. 

### Detailed summary
- Added `ru.l3r8y.sa-tan` dependency to `pom.xml`.
- Added `@Mutable` annotation to `Cached` class.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by zoeself** [comment]
@h1alexbel thank you for your Pull Request. I'll assign someone to review it soon. 

 If this PR solves a ``todo`` from the code, please don't forget to remove it.

**Comment by zoeself** [comment]
@h1alexbel please review this Pull Request. Deadline (when it should be merged or closed) is ``2023-07-07T15:19:05.967098``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by h1alexbel** [comment]
@rultor merge

**Comment by zoeself** [comment]
@h1alexbel thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
