### PR TITLE
jsonof assertions

### PR DESCRIPTION
**Pull request by h1alexbel**
### Focus of this PR
This PR focuses on adding test cases for the `JsonOf` class.

### Detailed summary
- Added test cases for constructing `JsonOf` from bytes, string, input stream, `JsonNode`, and file
- Added test case for reading bytes of a JSON array
- Added test case for stringifying a malformed JSON
- Added test case for reading JSON multiple times
- Added test case for caching file contents when reading JSON from a file

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by zoeself** [comment]
@h1alexbel thank you for your Pull Request. I'll assign someone to review it soon. 

 If this PR solves a ``todo`` from the code, please don't forget to remove it.

**Comment by h1alexbel** [comment]
@rultor merge

**Comment by zoeself** [comment]
@h1alexbel please review this Pull Request. Deadline (when it should be merged or closed) is ``2023-07-02T10:39:04.329994``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by zoeself** [comment]
@h1alexbel thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
