### PR TITLE
Json.Of migration

### LINKED ISSUE #27: migrate `Json.Of` to `JsonOf`

### PR DESCRIPTION
**Pull request by h1alexbel**
closes #27

---

## PR-Codex overview
This PR replaces the `Json.Of` class with the `JsonOf` decorator. It also replaces all references to `Json.Of` with `JsonOf`, and updates the affected tests.

### Detailed summary
- Replaces `Json.Of` with `JsonOf` decorator
- Updates all references to `Json.Of` with `JsonOf`
- Updates affected tests

> The following files were skipped due to too many changes: `src/test/java/io/github/eocqrs/eokson/SmartJsonTest.java`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by zoeself** [comment]
@h1alexbel thank you for your Pull Request. I'll assign someone to review it soon. 

 If this PR solves a ``todo`` from the code, please don't forget to remove it.

**Comment by zoeself** [comment]
@h1alexbel please review this Pull Request. Deadline (when it should be merged or closed) is ``2023-06-28T11:39:03.995839``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by h1alexbel** [comment]
since, JsonProcessing exception cannot be thrown in jackson version > `2.1`, test can not be introduced

**Comment by zoeself** [comment]
@h1alexbel thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
