### PR TITLE
JsonXML readme

### LINKED ISSUE #52: json to xml readme

### PR DESCRIPTION
**Pull request by h1alexbel**
closes #52 

---

### Detailed summary

This PR focuses on adding functionality to transform JSON to XML using the JsonXML library. The notable changes include:

- Added code example for transforming JSON to XML using JsonXML library
- Added code example for integrating with jcabi-xml library

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by zoeself** [comment]
@h1alexbel thank you for your Pull Request. I'll assign someone to review it soon. 

 If this PR solves a ``todo`` from the code, please don't forget to remove it.

**Comment by h1alexbel** [comment]
@rultor mere

**Comment by h1alexbel** [comment]
@rultor merge

**Comment by zoeself** [comment]
@h1alexbel thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request merged**
